#!/usr/bin/bash
readonly LIBXML2_VERSION="2.7.1"
readonly NGINX_VERSION="1.18.0"
readonly PHP_VERSION="7.2.29"
readonly MYSQL_VERSION="8.0.21"
readonly INSTALL_PATH=/opt/software
readonly DOWNLOAD_FOLDER=`pwd`/../download
readonly TMP_FOLDER=`pwd`/tmp


if [ ! -d $TMP_FOLDER ]
then
  mkdir ${TMP_FOLDER}
fi

if [ ! -d $INSTALL_PATH ]
then
  mkdir ${INSTALL_PATH}
fi


yum install -y gcc

source ./shell/php
source ./shell/nginx

